name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: JSDoc Action
      uses: andstor/jsdoc-action@v1.2.1
      with:
        source_dir: ./src
        recurse: true
        output_dir: ./public
