name: GitHub pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: node setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src
          output_dir: ./public
          config_file: ./jsdoc.json
          template: minami
          front_page: README.md
